name: ci

on:
  pull_request:
    branches:
      - latest
  push:
    branches:
      - latest

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.4
          - 8.5
        dependencies:
          - stable
          - lowest
    env:
      DEPENDENCY_VERSIONS: ${{ matrix.dependencies }}
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: 'false'
      - uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: docker compose pull --quiet
      - run: task ci
