name: ci

on:
    push:
        branches: [latest]

    pull_request:
        branches: [latest]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker-compose pull --quiet
            - run: make ci
